### ISSUE TITLE
Turn logger off with argument

### ISSUE THREAD

**Issue by lizgzil** [ivyleavedtoadflax/nervaluate#11]
The logger might not always be needed and can get annoying if you are evaluating lots of times in a loop, so it'd be nice to be able to turn it off.

I usually turn it off by:
```
import logging

logger = logging.getLogger()
logger.setLevel(logging.CRITICAL)
```

but an argument to Evaluator would be nicer.

**Comment by ivyleavedtoadflax** [comment]
Do you think this is just a matter of reducing its verbosity?

**Comment by ivyleavedtoadflax** [comment]
Another option might be to allow you to pass your own logger if not using the default.

**Comment by lizgzil** [comment]
> Do you think this is just a matter of reducing its verbosity?

I think turning it off completely would be useful. Just thinking of a time where you might be finding some metrics using nervaluate every iteration when training and the logs disrupt your nice output, e.g.
```
---------------
BATCH | LOSS
---------------
0       67.40
1       25.85
2       19.95
```
might look like this with the logs on: 
```
---------------
BATCH | LOSS
---------------
2019-12-03 14:53:19 root INFO: Imported 3 predictions for 3 true examples
0       60.72
2019-12-03 14:53:19 root INFO: Imported 3 predictions for 3 true examples
1       19.79
2019-12-03 14:53:19 root INFO: Imported 4 predictions for 4 true examples
2       11.26
```

**Comment by ivyleavedtoadflax** [comment]
Ah yeah i think that just needs to move to being `debug` rather than `info`. that will probably solve the issue.
