### ISSUE TITLE
Add F1 to evaluate output

### ISSUE THREAD

**Issue by lizgzil** [ivyleavedtoadflax/nervaluate#12]
It'd be good to have a F1 score in the nervaluate output. I personally have to always calculate this after anyway, e.g.
```
evaluator = Evaluator(true_doc_entities, pred_doc_entities, tags=tags)
results, _ = evaluator.evaluate()
f1 = f1_score(results['partial']['precision'], results['partial']['recall'])
```

**Comment by ivyleavedtoadflax** [comment]
Can I tempt you to make a PR?

**Comment by lizgzil** [comment]
@ivyleavedtoadflax sure!

**Comment by lizgzil** [comment]
Done in https://github.com/ivyleavedtoadflax/nervaluate/pull/16
