### ISSUE TITLE
Inconsistent behavior when loading from list

### ISSUE THREAD

**Issue by pimmeerdink** [ivyleavedtoadflax/nervaluate#27]
Hey guys @davidsbatista @ivyleavedtoadflax ,

Using this package to evaluate a NER-tagger I built. It only has to recognize one type of entity so the tags is a list with an empty string. Basically: when i run the following:
`t = [['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B', 'I']] `
 `p = [['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B', 'I', 'O', 'O', 'O', 'O', 'B', 'I']] `
`evaluator = Evaluator(t,p, tags= [''], loader='list')`
`evaluator.evaluate()`

I get 

`({'ent_type': {'correct': 0, 'incorrect': 0, 'partial': 0, 'missed': 0, 'spurious': 1, 'possible': 0, 'actual': 1, 'precision': 0.0, 'recall': 0, 'f1': 0}, 'partial': {'correct': 0, 'incorrect': 0, 'partial': 0, 'missed': 0, 'spurious': 1, 'possible': 0, 'actual': 1, 'precision': 0.0, 'recall': 0, 'f1': 0}, 'strict': {'correct': 0, 'incorrect': 0, 'partial': 0, 'missed': 0, 'spurious': 1, 'possible': 0, 'actual': 1, 'precision': 0.0, 'recall': 0, 'f1': 0}, 'exact': {'correct': 0, 'incorrect': 0, 'partial': 0, 'missed': 0, 'spurious': 1, 'possible': 0, 'actual': 1, 'precision': 0.0, 'recall': 0, 'f1': 0}}, {'': {'ent_type': {'correct': 0, 'incorrect': 0, 'partial': 0, 'missed': 0, 'spurious': 1, 'possible': 0, 'actual': 1, 'precision': 0.0, 'recall': 0, 'f1': 0}, 'partial': {'correct': 0, 'incorrect': 0, 'partial': 0, 'missed': 0, 'spurious': 1, 'possible': 0, 'actual': 1, 'precision': 0.0, 'recall': 0, 'f1': 0}, 'strict': {'correct': 0, 'incorrect': 0, 'partial': 0, 'missed': 0, 'spurious': 1, 'possible': 0, 'actual': 1, 'precision': 0.0, 'recall': 0, 'f1': 0}, 'exact': {'correct': 0, 'incorrect': 0, 'partial': 0, 'missed': 0, 'spurious': 1, 'possible': 0, 'actual': 1, 'precision': 0.0, 'recall': 0, 'f1': 0}}})
`
Whats notable, is that its 'possible' is 0  for all evaluation methods, while clearly there is a tag present in the true list. The same is true for the 'actual': it fails to find the last present tag, leading me to believe the problem is in the loading of the data. This problem occurs more frequently.

Any ideas? 

Pim

**Comment by pimmeerdink** [comment]
I have a fix, it's very small, unable to push it though.

**Comment by ivyleavedtoadflax** [comment]
Hey @pimmeerdink thanks for raising this issue. Are you able to fork the repo and push a fix from your fork?

Have you also seen #25 which was raised recently about the number of possible tags?

**Comment by pimmeerdink** [comment]
Hey @ivyleavedtoadflax, 

Cloned the repo, made a new branch, tried to push but was unable to:
```
remote: Permission to ivyleavedtoadflax/nervaluate.git denied to pimmeerdink.
fatal: unable to access 'https://github.com/ivyleavedtoadflax/nervaluate.git/': The requested URL returned error: 403
```

**Comment by ivyleavedtoadflax** [comment]
So you'll need to create a fork on github, push your changes to your fork, then create a pull request to allow you to push changes over to this repo. This will guide you through it: https://github.com/firstcontributions/first-contributions

**Comment by ivyleavedtoadflax** [comment]
Hey @pimmeerdink let me know if you need a hand pushing your changes.

**Comment by pimmeerdink** [comment]
Hey sorry forgot to @ you in the pull request, you should see it now?

**Comment by ivyleavedtoadflax** [comment]
ah great, sorry yes i missed that!

**Comment by ivyleavedtoadflax** [comment]
Thanks @pimmeerdink  :+1:
